eBay/NuRaft

README.md
src/buffer_serializer.cxx

* Also added instruction for Windows in README.md.

Fix compile errors on Windows

---

.travis.yml
travis_build.sh

* Pull request: run test with address sanitizer.
* Other branches: run test with code coverage job.

Add code coverage test job

---

include/libnuraft/raft_server.hxx
src/raft_server.cxx
tests/unit/raft_package_fake.hxx
tests/unit/raft_server_test.cxx

* Added an option for skipping initialization of election timer.

Add init option for `raft_server` constructor

---

CMakeLists.txt
tests/CMakeLists.txt

* Added target for compiling shared library.

Support shared library

---

CMakeLists.txt

* Need to link dependencies for shared library.

Fix compile errors on Mac

---

src/handle_append_entries.cxx

* If a follower is not responding, should limit the number of logs to 1.

Fix to regression caused by recent append_entries() change

---

src/handle_append_entries.cxx
tests/unit/failure_test.cxx
tests/unit/raft_functional_common.hxx

* Rollback should be called for each log entry, in descending order.

Fix a bug in rollback on log conflict

---

src/asio_service.cxx

* Corrected wrong `stopping_status_` value, it should be 0 or 2.
* Count the number of exceptions globally.

Fix to bug in Asio exception handling

---

tests/unit/asio_service_test.cxx

Fix a test issue: random denial test

---

src/handle_append_entries.cxx

* We should do rollback only when we have at least one log to overwrite.

Fix a bug on rollback

---

include/libnuraft/raft_server.hxx
src/handle_append_entries.cxx

* Also added detailed comment about a possible case on rollback.

Add new API to get target commit index

---

tests/unit/failure_test.cxx

Fix testing issue

---

src/raft_server.cxx

* Single node cluster is not allowed to do resignation.

Do not yield leadership if it is the only node

---

src/handle_append_entries.cxx
src/handle_timeout.cxx

* It will block removing it from peer list.
* Corrected the timeout interval for force removing: should use
LEAVE_LIMIT.

Do not re-establish connection to to-be-removed server

---

src/raft_server.cxx

* Once a server becomes leader, it appends a new config log. But that
should not modify the previous config which is already committed.
* It sometimes causes a bug skipping config log commit, due to
`config log index == prev log index`.

Do not modify committed config on becoming leader

---

include/libnuraft/peer.hxx
include/libnuraft/raft_server.hxx
src/handle_append_entries.cxx
src/handle_join_leave.cxx
src/handle_timeout.cxx
src/handle_vote.cxx
src/raft_server.cxx

Get rid of hard-coded limits

---

src/handle_append_entries.cxx

* Upon term mismatch, leader and follower find the last matching log
index by backward scanning. Printing log for each scanning step will
be verbose.
* Now it will print a log for every 500 ms. If someone wants to see
the full version of logs, need to use trace level.

Suppress verbose logs during backward scanning

---

include/libnuraft/raft_server.hxx
src/handle_custom_notification.cxx
src/handle_custom_notification.hxx
src/raft_server.cxx
tests/unit/raft_server_test.cxx

* Any follower can request the current leader to yield leadership so
as to become the next leader.

Add an API to take leadership

---

.gitignore
include/libnuraft/basic_types.hxx

- add build to .gitignore
- enclose typedefs with namespace in basic_type.hxx

add build to .gitignore and  enclose typedefs with namespace in basic_type.hxx

---

src/handle_commit.cxx

use find() instead of loop for getting entry from commit_ret_elems_

use find() instead of loop for getting entry from commit_ret_elems_

---

src/handle_append_entries.cxx

More explicit logging on state machine rollback

---

.clang-format
include/libnuraft/raft_params.hxx
include/libnuraft/rpc_cli.hxx
src/asio_service.cxx
tests/unit/asio_service_test.cxx
tests/unit/fake_network.cxx
tests/unit/raft_package_asio.hxx

[Refactor] Format change

---

include/libnuraft/raft_server.hxx
src/raft_server.cxx

The most simple solution for the problem from issue https://github.com/eBay/NuRaft/issues/194.

Optionally move server startup to separate method

---

include/libnuraft/raft_server.hxx
src/raft_server.cxx
tests/unit/asio_service_test.cxx

* The new API returns the last log index and response time.

Add APIs to get peer info

---

src/handle_commit.cxx
tests/unit/raft_package_fake.hxx
tests/unit/raft_server_test.cxx

* Replaying config log shouldn't result in reverting committed
configurations.

Add test for replaying config log

---

README.md
include/libnuraft/buffer_serializer.hxx

* `buffer_serializer` should include `string`.
* Modified README.md to fetch the correct Asio version.

Fix to Windows build

---

src/handle_commit.cxx

Fix https://github.com/eBay/NuRaft/issues/241

Add conf condition at the beginning of snapshot_and_compact.

---

include/libnuraft/raft_params.hxx
src/handle_append_entries.cxx
tests/unit/asio_service_test.cxx
tests/unit/raft_server_test.cxx

* Even though a few unhealthy members exist, if the number of healthy
members is greater than the regular quorum size, we will pursue the
full consensus among them.

Revise full consensus mode

---

include/libnuraft/state_machine.hxx
src/handle_append_entries.cxx
tests/unit/asio_service_test.cxx
tests/unit/raft_functional_common.hxx

* User can adjust commit index based on the list of peers' log indexes.

Add a new callback for custom quorum condition

---

src/raft_server.cxx

* Server role should be changed BEFORE accepting the newer term.

Fix to race between `update_term` and `handle_cli_req`

---

src/handle_client_request.cxx
src/handle_client_request.hxx
src/handle_commit.cxx

Fix to `commit_ret_elem` leak when client timeout

---

include/libnuraft/raft_params.hxx
include/libnuraft/raft_server.hxx
src/handle_commit.cxx
src/raft_server.cxx
tests/unit/raft_server_test.cxx

avoid simultaneously snapshot

---

include/libnuraft/raft_server.hxx
src/handle_commit.cxx
src/handle_snapshot_sync.cxx
src/raft_server.cxx

* Instead of busy waiting, we can sleep and wake up by a notification.

Add an API to get the notification of state machine pause

---

CMakeLists.txt

* `cmake -DOPENSSL_LIBRARY_PATH=... -DOPENSSL_INCLUDE_PATH=...`

Support manual OpenSSL path

---

include/libnuraft/raft_server.hxx
src/raft_server.cxx
tests/unit/failure_test.cxx
tests/unit/raft_package_fake.hxx
tests/unit/raft_server_test.cxx

Check election timeout lower and upper bound.

Checking parameters

---

src/tracer.hxx
tests/unit/asio_service_test.cxx

1. do nothing in ssl_test() when build with -DDISABLE_SSL=1 
3. add printf format check for log

1. do nothing in ssl_test() when build with -DDISABLE_SSL=1   2. add printf format check for log

---

.gitignore
.gitmodules
README.md
prepare.sh

in this way this project can be used directly as submodule without problem and without calling the ./prepare.sh script

add asio as module

---

include/libnuraft/logger.hxx
include/libnuraft/msg_type.hxx
include/libnuraft/resp_msg.hxx
include/libnuraft/rpc_exception.hxx
include/libnuraft/rpc_listener.hxx
include/libnuraft/srv_role.hxx
include/libnuraft/state_mgr.hxx
include/libnuraft/strfmt.hxx
src/buffer.cxx

- Add missing header files.
- Don't implement functions in header files.

Add missing header files and don't implement functions in header files

---

examples/backtrace.h
examples/logger.cc
src/handle_commit.cxx
src/raft_server.cxx
tests/unit/asio_service_test.cxx

* To avoid buffer overflow, `sprintf` shouldn't be used.

Replace `sprintf` with `snprintf` or `stringstream`

---

src/asio_service.cxx

* Initializing `ssl_context` with `SSL_CTX*` is supported Asio later than 1.16.1.

Fix compile error for old version of Asio

---

.github/dependabot.yml
.github/workflows/cmake.yml
github_action_build.sh
travis_build.sh

Fixes https://github.com/eBay/NuRaft/issues/424
Used OpenSSF Security Scorecard to identify and mitigate weaknesses in [NuRaft](https://github.com/eBay/NuRaft). Raised the project's score from 5.5 to 10. See branch https://github.com/lucasgonze/NuRaft/pull/new/pin-dependencies
1. Pinned dependencies in cmake.yml. This prevents attacks via upstream actions. See https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/docs/checks.md#pinned-dependencies
2. Set token permissions to read-only in cmake.yml. This follows the principle of least privilege. This is important because attackers may use a compromised token with write access to push malicious code into the project.
3. Moved inclusion of CodeCov for code coverage metrics to a Github Action from …

Identify and mitigate weaknesses

---

include/libnuraft/log_store.hxx

Fixed grammar in comment to remove duplication

Update grammar in log_store.hxx comment

---

include/libnuraft/log_val_type.hxx
src/handle_priority.cxx

* `app_log` should be used for user data only.

Use `custom` type for priority change broadcast message

---

include/libnuraft/callback.hxx
src/raft_server.cxx
tests/unit/raft_package_asio.hxx
tests/unit/raft_server_test.cxx

* Callback can decline the resignation request.

Add a callback for leader resignation

---

.github/workflows/cmake.yml

* Until the below issue is fixed: https://github.com/actions/runner-images/issues/9524

Add fix to kernel mmap rnd bit to github action script

---

src/peer.cxx
src/raft_server.cxx

1. process response from stale connection
2. reset stream when become follower to make sure that stream will not affect election

Enhance Stream

---

tests/unit/asio_service_test.cxx

* To make sure `BecomeFollower` is invoked for members when they are added, even with `new_joiner_` option.

Add a test case to check `BecomeFollower` callback

---

CMakeLists.txt
docs/customizing_asio.md
docs/how_to_use.md
scripts/test/runtests.sh
tests/CMakeLists.txt

* Once this flag is given, Asio service won't be included in the library. The user is responsible for implementing network layer as well as thread pool and timer.

Add a compile flag to disable Asio

---

include/libnuraft/raft_params.hxx
include/libnuraft/raft_server.hxx
src/raft_server.cxx
tests/asio/asio_test_common.hxx
tests/asio/custom_quorum_test.cxx

* It should work even with streaming mode.

Add more test cases for full consensus mode

---

src/snapshot_sync_ctx.cxx

* If 1) async snapshot IO is on, and 2) a server is removed, and 3) snapshot transmission to that server is in progress, there might be a race condition that the server is removed from the peer list but the previous snapshot request is processed by the snapshot event loop later. That results in crash.

Fix to race between BG snapshot and removing server

---

src/handle_append_entries.cxx
src/handle_commit.cxx

* Should use `min`, not `max`.

Fix to bugs of peer tracking mode
