eBay/NuRaft

.codecov.yml, docs/custom_quorum_size.md, include/libnuraft/context.hxx, include/libnuraft/raft_server.hxx, src/crc32.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx, tests/unit/failure_test.cxx, tests/unit/raft_server_test.cxx
* Dealing with raw pointer is error-prone. They should return and
accept `shared_ptr`.
=> Adapt `get_current_params` and `update_params`

docs/custom_quorum_size.md, include/libnuraft/context.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/launcher.cxx, src/raft_server.cxx, tests/bench/raft_bench.cxx, tests/unit/asio_service_test.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_asio.hxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* `raft_params` is just a simple structure and there is no reason to
block copy operation.
* Modified related APIs.
=> Allow copy constructor for `raft_params`

examples/in_memory_log_store.cxx, include/libnuraft/log_store.hxx
* `write_at` API should purge all stale logs whose indexes are greater
than given index.
* Modified in-memory log store properly.
=> Add missing description of `write_at` API

CMakeLists.txt, docs/async_replication.md, docs/basic_operations.md, docs/custom_quorum_size.md, docs/dealing_with_buffer.md, docs/enabling_ssl.md, docs/how_to_use.md, docs/leader_election_priority.md, docs/leadership_expiration.md, docs/quick_start_guide.md, docs/quick_tutorial.md, docs/readonly_member.md, docs/snapshot_transmission.md, examples/quick_start.cxx
* Also corrected wrong header file path in MD documents.
=> Add quick tutorial

src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_snapshot_sync.cxx, src/raft_server.cxx
* Fatal errors that we must not reach cannot be verified by using
functional tests.
* Also excluded legacy snapshot type (i.e., `raw_binary`).
=> Exclude fatal errors from code coverage report

examples/echo/echo_server.cxx
=> Use buffer serializer in echo example

src/handle_commit.cxx, src/handle_join_leave.cxx
* A new node is not completely added to the cluster yet, at the time
when `handle_join_cluster_req` is called. Actual addition is done by
committing the configuration log, which is in `reconfigure`.
* Moved callback to there.
=> Move `JoinedCluster` callback to `reconfigure`

include/libnuraft/raft_server.hxx, src/handle_timeout.cxx
The idea is the following.  For the provision workflow, the following would happen:
1. Every node is started with `skip_initial_election_timeout_ = true`.
2. The agent will pick one node, and call `/initialize` on this node.  At this time `restart_election_timer()` will be called to elect this node to be the leader.
The idea is to make `/startserver` consistent among all nodes, and use the `/initialize` call to make the designated node the leader.
=> Expose restart election timer. 

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/handle_join_leave.cxx, src/handle_timeout.cxx, src/raft_server.cxx
* To reduce the uncertainty of leader reelection, the current leader
should pause write, and finish the catch-up of the latest log with the
highest priority peer (excluding myself) node. Then most likely that
peer node will be elected as a next leader.
=> Support graceful resignation of leader

examples/in_memory_log_store.cxx, examples/logger.cc, examples/logger.h, src/handle_append_entries.cxx, src/handle_timeout.cxx, tests/unit/failure_test.cxx
* If there is no snapshot, and logs are already compacted, leader
should protect itself rather than crashing.
* Update logger to fix recursive crash handler issue.
=> Handle the case when log do not exist

src/error_code.cxx, tests/unit/failure_test.cxx
* In failure test, we need to make sure commit happened before force
log compaction.
* Typo: missing comma(,) in error code description.
=> Fix test issues

include/libnuraft/log_store.hxx, src/handle_append_entries.cxx
The idea is to allow the underlying log store to return error in case it cannot retrieve the requested logs.  In this case, the raft should try to use snapshot to recover, similar to the case where the requested log out of the range available from the log store.
=> Improve error handling on log_entries_ext().

src/buffer_serializer.cxx
* `chk_length` should take actual value, not `sizeof(...)`. It will
always calculate the length as 8 bytes (in 64-bit machine).
* Fixed a typo: `uint32_t` -> `int32_t`
=> Fix a bug in serializer validity checking logic

CMakeLists.txt, include/libnuraft/callback.hxx, include/libnuraft/internal_timer.hxx, include/libnuraft/msg_base.hxx, include/libnuraft/msg_type.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/req_msg.hxx, src/handle_append_entries.cxx, src/handle_custom_notification.cxx, src/handle_custom_notification.hxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx, tests/unit/serialization_test.cxx
* Currently we are using this protocol for the notification of
out-of-log-range for lagging follower, in case when log has been
compacted without creating any snapshots (it should not happen in
normal case, must be user's fault).
* Added a new callback type for out-of-log-range, so that user can
handle this situation smoothly, rather than crash or abort.
=> Add a new protocol for custom notification

src/handle_custom_notification.cxx
* We should avoid false leader election.
=> Reset election timer in out-of-log handler

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_custom_notification.cxx, src/handle_custom_notification.hxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* Once "yield leadership" is requested, the current leader chooses the
next leader. It pauses incoming writes, and waits until the next leader
candidate fully catches up the current latest log. After that, the
current leader sends a custom notification to that candidate.
* Once the next leader candidate receives the notification, it
immediately initiates a special vote which will ignore the current
priority, so that it can be the next leader quickly.
=> Support active leadership takeover

include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_priority.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/fake_network.cxx, tests/unit/fake_network.hxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_server_test.cxx
* There can be an edge case where zero-priority member is the only
node who has the latest log, while all the other nodes with the latest
log are offline. In such case, next leader will never be elected as
the zero-priority member will reject all vote request.
* In such case, the zero-priority member should be a temporary leader.
Once it becomes a leader, it should do graceful resignation immediately;
waits for catching-up and then sends leadership takeover request to the
highest priority node.
* Added a new parameter for this option, and enabled by default.
=> Allow zero-priority member to be temporary leader

src/asio_service.cxx, tests/unit/asio_service_test.cxx
* If response meta callback function returns `false`, it will cause
null pointer access.
* Added random denial test.
=> Fix to crash in response meta callback

include/libnuraft/raft_server.hxx, src/handle_commit.cxx, tests/unit/raft_server_test.cxx
* For recovery purpose, we need a feature to apply config logs while
Raft server is still offline.
=> Add a new API for offline application of config log

src/handle_append_entries.cxx
* Followers always should commit on received logs only, as leader may
send empty payload with the latest committed index. If some logs that
the follower currently has are stale so that need to be rolled back,
they can be incorrectly committed by this request.
=> Fix to bug on committing logs to be rolled back

src/asio_service.cxx, src/handle_commit.cxx
* To help debugging and profiling.
=> Assign unique name to each worker thread

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* When a new leader is elected before the config change from old leader
is committed, there was a bug that new leader ignores all uncommitted
config change.
* When a node becomes a new leader, it should scan all uncommitted
configs and generate a new config on top of the last one.
=> Fix a bug that new leader ignores uncommitted config change

include/libnuraft/async.hxx, include/libnuraft/context.hxx, include/libnuraft/error_code.hxx, include/libnuraft/pp_util.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/error_code.cxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_snapshot_sync.cxx, src/handle_timeout.cxx, src/peer.cxx, src/raft_server.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_package_fake.hxx
* Added a new background thread to create append_entries request.
* Now `append_entries` request will not grab `lock_` by default.
* Above options are configurable.
=> Separate user API from central lock

src/handle_append_entries.cxx, tests/unit/fake_network.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* Once a new node is added to existing cluster, it should clear the
`catching_up_` flag only after it is successfully added to the
cluster member list (i.e., config commit). Otherwise, there might be
any prior membership change configs that is already outdated so that
does not contain the new node. Then new node will treat it as an
abandon from the cluster so that step down itself.
=> Fix to bug regarding stepping down newly added node

examples/example_common.hxx, include/libnuraft/launcher.hxx, src/asio_service.cxx, src/launcher.cxx
* Most likely wrong endpoint causes exception. We should gracefully
handle it.
=> Throw exception on listener creation error

src/handle_commit.cxx
* It is better to start election timer as a part of config commit,
before waiting for the first heartbeat.
=> Immediately start election timer on config commit

include/libnuraft/srv_state.hxx, src/handle_timeout.cxx, src/raft_server.cxx
* We need a state that a server in a single-node cluster doesn't
trigger leader election to avoid being a self-elected leader. And
this state should be persistent, even after process restart.
* This state can be used for removed server: which already stepped
down itself. It shouldn't be a leader after process restart.
=> Add new state: election_timer_allowed

include/libnuraft/raft_server.hxx, src/handle_timeout.cxx, src/raft_server.cxx
* Election timer flag should be updated on election timer restart,
as the flag will not be effective anymore if timer is initiated.
=> Allow election timer on restart_election_timer API

src/handle_commit.cxx, src/handle_timeout.cxx, tests/unit/raft_server_test.cxx
* Now we have a persistent flag for election timer, we don't need to
append dummy log which causes log diverging if this server re-joins
the existing cluster.
=> Do not append dummy config log for removed server

tests/unit/failure_test.cxx
* There shouldn't be in-flight req/resp before removing server, for
deterministic testing (the traversal order of unordered_map in Mac is
different to that in Linux).
=> Fix an issue on `uncommitted_conf_new_leader_test`

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_timeout.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx
* We should not remove the server from the list immediately,
due to the issue as follows:
0) Let's suppose there are 3 servers: S1, S2, and S3,
where S1 is the leader and S3 is going to leave.
1) Generate a conf log for removing server S3.
2) The conf log is committed by S1 and S2 only.
3) Before delivering the conf log to S3, S1 removes
the S3 peer info from the list.
4) It closes the connection to S3.
5) S3 cannot commit the config (containing removing S3).
6) Callback function for `RemovedFromCluster` will be missing,
but S3 will step down itself after 2 timeout period.
* To address it, we will remove S3 only after the commit index
of the last config is delivered to S3. Also we will have timeout
for it. If we fail to deliver the commit index, S3 will be just
force removed.
=> Do not remove server from peer list immediately

include/libnuraft/async.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_timeout.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/raft_server_test.cxx
* To-be-removed server should be treated the same as learner.
* Set `srv_to_leave_` earlier than commit, to reduce one RPC to remove
a server.
=> Do not count to-be-removed server in quorum

src/raft_server.cxx
* If the number of members in a cluster is the same as the size of
quorum, giving up leadership does not help anything. We should keep
the leader alive.
=> Do not give up leadership when cluster is small

include/libnuraft/raft_params.hxx, src/handle_join_leave.cxx, src/raft_server.cxx
* If log sync gap is set to zero, newly joined server will be added to
the peer list immediately, without any sync-up.
* Reformatted comments based on doxygen style.
=> Support zero log sync gap

src/handle_commit.cxx, src/handle_join_leave.cxx, src/raft_server.cxx, tests/unit/raft_server_test.cxx
* Once RPC to to-be-removed server fails, we don't need to wait for
LEAVE_LIMIT and immediately proceed new configuration.
* The server will be eventually removed from the peer list after
LEAVE_LIMIT since the new config is committed.
=> Fix a bug on handling removing server RPC error

src/handle_timeout.cxx
* Since we count RPC error as an activity, we may not meet the condition
to remove `srv_to_leave_`, if there is continuous traffic and the leader
tries to reach the server.
* Instead we should use resp timer, which doesn't count error as a
valid activity.
=> `srv_to_leave_` timeout should use resp timer

src/handle_append_entries.cxx, src/handle_join_leave.cxx
* When we check the response from to-be-removed server, we should
make sure that its last log index is bigger than the target index.
If the to-be-removed server restarts, it may return response but
may not sync up the latest config yet.
* Adding server logic should check `srv_to_leave_` node is gone,
before duplicate ID checking.
=> Fix a couple of bugs on removing servers

include/libnuraft/raft_params.hxx, src/raft_server.cxx
* For 2-node cluster, we may need this option to make progress even
though a follower is receiving snapshot.
=> Add an option to exclude snapshot receiver from quorum

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/raft_server.cxx
If bg_append_ea_->invoke(); is invoked between reset() and wait() it will become a no-op, and the background append thread will wait forever.
Added other cosmetic changes to improve diagnostic logging.
=> Fix rare hang during raft_server->shutdown().

include/libnuraft/asio_service.hxx, include/libnuraft/peer.hxx, include/libnuraft/rpc_cli.hxx, src/asio_service.cxx, src/handle_append_entries.cxx, src/handle_join_leave.cxx, src/handle_priority.cxx, src/handle_vote.cxx, src/peer.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/fake_network.cxx, tests/unit/fake_network.hxx
* Both prevote and vote requests also should honor `busy_flag_` in
`peer`. Otherwise, race on the same client happens and it will result
in various memory corruptions.
=> Fix race on ASIO client during prevote and vote

src/handle_append_entries.cxx
* Since `peer::set_free()` is called prior than response handler
without acquiring `raft_server::lock_`, there can be an edge case
that leader may send duplicate logs, and their last log index may not
be greater than the last log index this server already has. We should
always compare the target index with current precommit index, and take
it only when it is greater than the previous one.
=> Fix to precommit/commit order inversion bug

include/libnuraft/peer.hxx, src/handle_commit.cxx, src/handle_join_leave.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx
* If `srv_to_leave_` is NULL on removing server in reconfigure, that
means Raft is replaying old log, and there is no current request by
user. In such case, we can skip the logic handling `srv_to_leave_`.
=> Skip processing `srv_to_leave_` on replaying old configs

include/libnuraft/raft_server.hxx, include/libnuraft/srv_state.hxx, src/raft_server.cxx, tests/unit/raft_server_test.cxx
* Instead of default logic (increasing by 1), some use cases need
a custom counter for term.
* Even in custom counter, term should be always increasing. But it
doesn't need to be consecutive.
=> Support custom term counter

include/libnuraft/callback.hxx, src/asio_service.cxx
* We should differentiate opening connection and receiving message
from valid leader, as leader can be changed without closing connection.
=> Add new callback event for new session from leader

include/libnuraft/raft_server.hxx, src/handle_vote.cxx
* Once a leader becomes a follower due to vote requests, its role
immediately changes, but `leader_id_` does not. It may cause an
issue returning a stale leader ID.
=> Fix to returning stale leader ID issue

include/libnuraft/peer.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx
* The quorum size of the 2-node cluster is 2, which means if any node
goes offline, the cluster becomes unavailable immediately.
* Added a configurable option: if we turn on this option, the quorum
size of the 2-node cluster is automatically adjusted to 1, if any
node becomes offline. The remaining node can do self-election and
also can commit incoming requests. The quorum size will be restored
using the default value once the offline node becomes online.
* It is not entirely safe, and dealing with log divergence is the
users' responsibility. Using the custom term counter to avoid
duplicate terms may be helpful.
=> Support auto adjusting quorum size for 2-node cluster

src/handle_append_entries.cxx
* If 2-node cluster's leader is sending snapshot, and if
`exclude_snp_receiver_from_quorum_` option is on, this case should be
handled separately.
=> Fix to bug on auto adjusting quorum size

include/libnuraft/raft_server.hxx, src/raft_server.cxx, tests/unit/raft_server_test.cxx
* Users can nominate the next leader upon `yield_leadership` call.
* If not given, the highest priority one will be chosen automatically.
=> Support designated successor for leadership yield

src/handle_join_leave.cxx
* If `handle_join_leave_rpc_err` is called but `srv_to_leave_` is
already set, that function is probably invoked by `handle_hb_timeout`.
In such a case, the server to be removed does not respond while the
leader already generated the log for the configuration change.
We should abandon the peer entry from `peers_`.
=> Handle an edge case of removing server

src/handle_user_cmd.cxx
In reference to issue #131. Compiles and passes all unit tests.
Thanks,
James.
=> Fixed bug where accept flag wasn't propagated correctly when using auto-forwarding

include/libnuraft/async.hxx, src/handle_user_cmd.cxx
I've added the wait method to the cmd_result class because calling get won't work due to how the presult variable is instantiated. 
https://github.com/eBay/NuRaft/blob/17aab8d633b0187dc4a5d862aa75faf3ef91f5cd/src/handle_user_cmd.cxx#L168-L170
When presult is made, it calls a constructor that sets has_result_ to true. Then, if get() was used it would see that has_result_ is true and return immediately and not wait for the set_result call. Therefore, the explicit wait method will guarantee the current thread to wait until a call to set_result happens.
=> Auto-forwarding now waits for a result when using blocking mode before returning

CMakeLists.txt, include/libnuraft/global_mgr.hxx, include/libnuraft/nuraft.hxx, include/libnuraft/raft_server.hxx, src/global_mgr.cxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/handle_commit.cxx, src/raft_server.cxx, src/stat_mgr.cxx, tests/unit/asio_service_test.cxx
* Each Raft instance creates at least two threads: one for commit and
the other one for append. If there is a use case that a process has
many Raft instances, it will produce lots of threads which end up with
resource efficiency problem.
* To address this issue, we introduce a global thread pool; there are
shared worker threads for commit and append, and a global manager
coordinates requests from multiple Raft instances and assigns them
to proper worker threads.
=> Support global workers for commit and append

include/libnuraft/global_mgr.hxx, src/global_mgr.cxx
* `worker_handle` does not need to be exposed.
=> Hide `worker_handle` and move it to cxx file

include/libnuraft/global_mgr.hxx, include/libnuraft/raft_server.hxx, src/handle_commit.cxx
* Racing between workers may cause verbose warnings, although it is
functionally correct by help of CAS.
=> Allow only one global worker to do commit of a Raft server

include/libnuraft/global_mgr.hxx, src/asio_service.cxx, src/global_mgr.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_package_asio.hxx
* In addition to append/commit workers, Asio workers also can be
shared among different Raft instances in the same process.
=> Support global Asio worker pool

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/raft_server.cxx
* We should use compare-and-swap to avoid the situation that
a pre-commit index update is reverted by the race between threads.
=> Fix to potential pre-commit order inversion

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/raft_server.cxx
* In a 2-node cluster, the lagging follower may result in blocking 
the commit of the leader, which affects the availability. We should 
be able to adjust the quorum size for that case as well.
=> Adjust quorum size for lagging follower as well

src/asio_service.cxx
* Set the minimum version of TLS as v1.2 for strong security
boost will call SSL_CTX_set_min_proto_version() to set the minimum protocol version
=> Forbid the old versions of TLS

include/libnuraft/launcher.hxx, include/libnuraft/raft_server.hxx, src/launcher.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx
support setting raft server init options and raft callback in raft_launcher::init()
=> support setting raft server init options and raft callback in raft_launcher::init()

include/libnuraft/callback.hxx, src/handle_commit.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* Added a new callback command for state machine execution. Now
`raft_server_test` will not rely on the timer, but deterministically
proceed the test according to the callback signal.
* TODO: Synchronous executor is still based on timing.
=> Make `raft_server_test` and `failure_test` deterministic

src/handle_vote.cxx
* While a server is catching up the leader, its `hb_alive_` flag will
not be updated properly, hence it will reject all pre-vote requests
which may block the leader election.
=> Accept pre-vote if `catching_up_` flag is on

src/handle_snapshot_sync.cxx
```
my id: 2, voting_member
num peers: 0 [raft_server.cxx:242, raft_server()]
2020-12-11T14:59:07.571_325+08:00 [c2c9] [INFO] global manager does not exist. will use local thread for commit and append [raft_server.cxx:253, raft_server()]
2020-12-11T14:59:07.571_405+08:00 [c2c9] [INFO] wait for HB, for 50 + [200, 400] ms [raft_server.cxx:280, raft_server()]
2020-12-11T14:59:07.571_527+08:00 [aeb7] [INFO] bg append_entries thread initiated [handle_append_entries.cxx:47, append_entries_in_bg()]
2020-12-11T14:59:07.642_937+08:00 [decf] [INFO] receive a incoming rpc connection [asio_service.cxx:759, handle_accept()]
2020-12-11T14:59:07.643_010+08:00 [decf] [INFO] session 1 got connection from 10.203.46.164:7672 (as a server) [asio_service.cxx:244, prepare_handshake()] …
```
=> [eBay][NuRaft][LOG] Correct error prompt

include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/state_machine.hxx, src/handle_append_entries.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx
* Added a configurable option that if there is a server in the same
group with higher priority, the leader will transfer its leadership
to the server if all other peers are healthy.
=> Support leadership transfer

README.md, src/asio_service.cxx
* Calling `remote_endpoint()` with invalid socket will cause an
unintended exception, which results in triggering self-defense
logic by exception handler.
=> Do not call `remote_endpoint()` on failed connection

src/handle_vote.cxx
All values (`live_`, `dead_`, `quorum_size`, `failure_count_`) are signed (except `term_`) and seem like in debug mode it can lead to undefined behavior during logging:
```
total 1 nodes (including this node) responded for pre-vote (term 1, live 0, dead 1), at least 139633681760258 
nodes should respond. failure count 15                                                                                                                                                                                                         ```
=> Fix formating specifiers in logging

src/asio_service.cxx, src/peer.cxx
* `handle_rpc_result` can be invoked asynchronously without Raft `lock_`,
hence `set_free()` should be called under `rpc_protector_`. Otherwise,
it may free the flag even though a new RPC client is created, which
results in race condition.
=> Clearing busy flag should be protected by lock

CMakeLists.txt
update `CMakeLists.txt` (`CMAKE_SOURCE_DIR` to `PROJECT_SOURCE_DIR`).
failed to generate Makefile when using `add_subdirectory`.
=> change to use PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

include/libnuraft/peer.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_vote.cxx, src/peer.cxx, src/raft_server.cxx, tests/unit/failure_test.cxx, tests/unit/raft_server_test.cxx
* To support offline data change (including snapshot installation),
peer's log info should be reset if the previous connection is gone.
Otherwise, there will be a data mismatch and the leader will attempt
to send logs based on incorrect info.
* The reset peer info will be recovered during the first
`append_entries` communication between the leader and the peer.
=> Reset peer's log info once new connection is established

tests/unit/failure_test.cxx
* This happens due to recent protocol change:
https://github.com/eBay/NuRaft/pull/182
=> Fix to intermittent test failure

src/handle_commit.cxx
Usage of condition variables without additional checks almost always leads to bugs. In this case, it may happen that `commit_cv` was notified before `commit_cv_lock_` was acquired. It can lead to a long wait until the next commit notification.
=> Fix rare race condition on commit cv

include/libnuraft/raft_params.hxx, include/libnuraft/rpc_cli.hxx, src/asio_service.cxx, src/handle_user_cmd.cxx, tests/unit/asio_service_test.cxx, tests/unit/fake_network.cxx, tests/unit/fake_network.hxx, tests/unit/raft_package_asio.hxx
Add `auto_forwarding_req_timeout_` setting which cancels forwarded request to the leader after the timeout.
=> Add optional timeout to auto_forwarded requests

include/libnuraft/global_mgr.hxx, src/global_mgr.cxx, src/raft_server.cxx, src/stat_mgr.cxx, src/stat_mgr.hxx
* The destruction order of global static variables is non-deterministic.
=> Get rid of auto_destoyer

include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_user_cmd.cxx, tests/unit/asio_service_test.cxx
* https://github.com/eBay/NuRaft/issues/184
* Added a new parameter `auto_forwarding_max_connections_`, and
auto-forwarding can be parallelized up to this number.
* Raft server is actively managing the RPC client so as to avoid
the race on the same connection.
* TODO: handling RPC timeout of auto-forwarding.
=> Make auto-forwarding serialized and parallel

include/libnuraft/raft_server.hxx, src/handle_user_cmd.cxx
* We should not expose the internal header to the public.
=> Get rid of event_awaiter.h from raft_server.hxx

tests/unit/fake_network.cxx, tests/unit/fake_network.hxx
* If we use `unordered_map`, its traversal order won't be deterministic
and depending on platforms the test executable is running. We should
make the test deterministic.
=> Make fake network transfer order deterministic

include/libnuraft/raft_server.hxx, src/handle_user_cmd.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx
* Should use lock for list manipulation.
* Added explicit shutdown for things related to auto-forwarding.
=> Fix to intermittent test failure of auto forwarding

include/libnuraft/debugging_options.hxx, src/peer.cxx, tests/unit/failure_test.cxx, tests/unit/raft_server_test.cxx
* For deterministic tests based on mock network layer (raft_server_test
and failure_test), we should disable back-off timer as it makes test
depend on the timing.
=> Disable reconnection back-off timer for deterministic tests

include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/state_machine.hxx, src/handle_commit.cxx, src/handle_snapshot_sync.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_package_asio.hxx, tests/unit/raft_server_test.cxx
* This option is used for avoiding a server being a leader, when
the server's state machine is lagging behind the last committed index.
=> Add an option for grace period

include/libnuraft/debugging_options.hxx, src/handle_client_request.cxx, src/handle_commit.cxx, src/peer.cxx, tests/unit/asio_service_test.cxx
* If the commit thread executes the state machine operation before the
user thread (in the middle of `append_entries`) installs the commit
element, the user's callback function can be missed.
* Commit thread should make sure that if order inversion is detected,
it should let user thread invoke the callback, by generating the
corresponding commit element initialized with the state machine result.
=> Fix to order inversion between commit and user threads

examples/calculator/calc_state_machine.hxx, examples/echo/echo_state_machine.hxx, examples/in_memory_log_store.cxx, include/libnuraft/internal_timer.hxx, include/libnuraft/peer.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/snapshot_sync_ctx.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_snapshot_sync.cxx, src/handle_timeout.cxx, src/peer.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_functional_common.hxx
* When snapshot receiver (follower) is not responding long time, the
snapshot and its user context should be closed after configured
timeout.
* The same timeout should be applied to below cases:
- When the snapshot receiver is removed from the group.
- When a new joining server is not responding.
=> Close snapshot context on timeout

tests/unit/asio_service_test.cxx
* Asio disconnection event is not immediately fired under code
coverage mode.
=> Fix the testing issue under code coverage mode

src/handle_append_entries.cxx
In the middle of making a plugin for Apache Traffic Server, found a bug where setting the logger to nullptr causes a segfault when adding servers.
```
[Switching to Thread 0x7ffff627b700 (LWP 276059)]
nuraft::raft_server::get_expected_committed_log_idx (this=0x5555555c03d0) at /home/duke/Git/NuRaft/src/handle_append_entries.cxx:982
982	    if (l_->get_level() >= 6) {
(gdb) bt
#0  nuraft::raft_server::get_expected_committed_log_idx (this=0x5555555c03d0) at /home/duke/Git/NuRaft/src/handle_append_entries.cxx:982
#1  0x00007ffff7ebc74c in nuraft::raft_server::handle_append_entries_resp (this=0x5555555c03d0, resp=...) at /home/duke/Git/NuRaft/src/handle_append_entries.cxx:848
#2  0x00007ffff7f20940 in nuraft::raft_server::handle_peer_resp (this=0x5555555c03d0, …
```
=> fix segfault when logger is set to nullptr

src/handle_commit.cxx, src/handle_join_leave.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* The config received during join request should be durable via the
state manager.
* During the replaying of logs, the newer config should not be
overwritten by the older config.
=> Fix to bug on the restart of joining server

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx
Added lifecycle callback functions for worker-thread start and stop.  The idea behind this PR is the following:
MonstorDB uses user-space update-copy-update (rcu) libraries to manage frequently-read-but-rarely-updated data structures. The library requires each participating thread to call a "register" function before its first use of the library and a "unregister" function before the termination of the thread's main function.  Currently, MonstorDB uses a thread-local boolean flag to track the thread's first use, and relies on another thread-local variable's destructor to call the "unregister" function.  It seems to work at the moment, but theoretically it depends on the order of thread-local variable's destruction order and may break in future in a very subtle way.  I'm planning to fix …
=> Add lifecycle callback functions for worker threads.

include/libnuraft/peer.hxx, src/handle_append_entries.cxx, src/raft_server.cxx
* `get_next_log_idx` may not be accurate if we want to get the last
log successfully sent to the peer.
=> Fix to bug in `get_peer_info`

src/raft_server.cxx
* If we use matched index, it can be reset to 0 on reconnection so
that the peer can be treated as "stale" incorrectly.
=> Use last accepted index for staleness checking

src/handle_vote.cxx, tests/unit/raft_server_test.cxx
* When a new member is added, its election timer is disabled until it
fully catches up with the leader. Suppose somehow the leader has a
problem so that a leader election is initiated. In that case, the
new member may refuse the vote request if the candidate's priority is
lower than its priority. Since the election timer is disabled, there
is no way to decrease the target priority of the new member;
consequently, the leader election will not succeed forever.
* To avoid such a situation, the new member in catch-up mode should
ignore priority for the vote.
=> Joining member should ignore priority

include/libnuraft/async.hxx, include/libnuraft/raft_server.hxx, src/asio_service.cxx, src/handle_client_request.cxx, src/handle_commit.cxx, src/handle_user_cmd.cxx, src/raft_server.cxx, src/raft_server_handler.hxx, tests/unit/fake_network.cxx, tests/unit/fake_network.hxx, tests/unit/raft_server_test.cxx
* With this API,
- User can set an expected term. `append_entries` will succeed only
if the current server's term matches, behaves similar to
compare-and-swap operation.
- User can set a callback function to know the log index and term
of the log that is just appended.
=> Add extended append_entries API

src/handle_vote.cxx
* If pre-vote is rejected and the server starts receiving heartbeat
again, the pre-vote rejection counter should be reset to 0. But
currently `become_follower` will not be called as role of the server
remains as `follower`.
=> Change role to candidate on initiating pre-vote

src/handle_commit.cxx
I think the code contains explicit comment. Fixes #239.
=> Fix bug in `commit_ret_elems` which lead to "live leak" in case of requests batch.

src/handle_append_entries.cxx
* The current commit index should contain quick commit index.
=> Fix to bug of adjust_commit_index API

examples/in_memory_log_store.cxx, examples/in_memory_log_store.hxx, include/libnuraft/internal_timer.hxx, include/libnuraft/log_store.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_functional_common.hxx
* If this flag is set, the leader can do log replication and log
appending in parallel, thus it can reduce the latency of write
operation path.
=> Support parallel log appending as an experimental feature

src/raft_server.cxx
Found an overflow ulong logging.
```
[BECOME LEADER] appended new config at -408072442
```
=> fix log ulong overflow

src/raft_server.cxx
Found an overflow int32 logging.
```
2 nodes (out of 3, 3 including learners) are not responding longer than 10000 ms, at least 1645066963648514 node        s (including leader) should be alive to proceed commit
```
=> Fix log output

src/raft_server.cxx
Bellow log is a leader changed to a follower.
When it cancel `commit_ret_elem`, leadership checking result is stell valid after  it become follower. 
```
6960837 2022.02.19 13:46:00.533834 [ 111598 ] {} <Information> RaftInstance: create snapshot idx 94081208049 log_term 1571 done: 4633373 us elapsed
6960838 2022.02.19 13:46:00.534057 [ 111586 ] {} <Information> RaftInstance: [PRE-VOTE REQ] my role leader, from peer 1, log term: req 1571 / mine 1571
6960839 last idx: req 94081208069 / mine 94081208069, term: req 1571 / mine 1571
6960840 HB alive
6960841 2022.02.19 13:46:00.534123 [ 111586 ] {} <Information> RaftInstance: pre-vote decision: X (deny)
6960842 2022.02.19 13:46:00.534161 [ 111581 ] {} <Information> RaftInstance: [PRE-VOTE REQ] my role leader, from peer 3, log term: req 1571 / …
```
=> little fix of check_leadership_validity

include/libnuraft/async.hxx, src/asio_service.cxx, tests/unit/asio_service_test.cxx
* In async mode, the commit result will be ready later. If the request
is come from the other server through auto-forwarding, the request
should wait for the result before returning the response.
=> Deliver commit results for auto-forwarding in async mode

tests/unit/asio_service_test.cxx
* The given timeout is too short for slow environment.
=> Fix to pausing state machine test issue

include/libnuraft/callback.hxx, src/handle_join_leave.cxx, src/raft_server.cxx
* Same as `BecomeLeader`, `BecomeFollower` needs to carry the term
number.
=> Pass term number through `BecomeFollower` callback

src/handle_custom_notification.cxx
* If we don't reset the timer, another vote can be initiate which will
disrupt the take over task.
=> Reset election timer on leadership take over request

include/libnuraft/raft_server.hxx, src/handle_commit.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_server_test.cxx
* `create_snapshot` will create a snapshot based on the latest committed
log index.
=> Add an API to manually create a snapshot

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_package_asio.hxx
* The custom resolver can be invoked before the default resolver in
order to resolve the endpoint in its own way.
=> Support custom resolver

src/asio_service.cxx, src/fix_format.hxx, src/handle_snapshot_sync.cxx, src/handle_timeout.cxx, src/handle_vote.cxx, src/tracer.hxx, tests/test_common.h, tests/unit/asio_service_test.cxx
this PR fixes the unportability of NuRaft, now NuRaft could finally works on 32bit systems.
1. core problem is the widely-used typedef `nuraft::ulong` is defined as `uint64_t`, which is 8 bytes. on 64bit systems, 8B integer is defined as `unsigned long` which could be printed with `%ld` / `%lu`, but on 32bit systems, 8B integer should only be printed with `%lld` / `%llu`, if not doing so, the following data would have wrong offset, **causing the whole program be terminated by segfault.**
2. another problem is that NuRaft use a lot of `%zu` / `%z` (which is print a `size_t`) to print `nuraft:ulong`, **this could also cause segfault on 32bit systems**, since `size_t` is actually _shorter than_ 8B, as demonstrated in the following demo:
on armhf SoC and x86_32 (32bit):
```
root@ATK-IMX6U:~# …
```
=> fix segfault on 32bit system: fix #243, fix #362

include/libnuraft/raft_params.hxx
Really small fix to make it more consistent and to make MSAN happy 😄 (it was caught in our CI https://github.com/ClickHouse/ClickHouse/pull/39609)
=> Initialize parallel_log_appending

examples/in_memory_log_store.cxx, include/libnuraft/asio_service_options.hxx, include/libnuraft/log_entry.hxx, include/libnuraft/raft_server.hxx, src/asio_service.cxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/handle_join_leave.cxx, src/handle_priority.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_package_asio.hxx
* Added an option that enables automatic generation of timestamp
for each log entry. Log store implementation should be able to
store and load timestamps in log entries.
=> Support timestamp for log entry

include/libnuraft/internal_timer.hxx
Convert call to gettimeofday() (POSIX only) to use C++11 APIs available on all platforms.
=> Windows does not include POSIX gettimeofday() call.

src/handle_commit.cxx, src/handle_snapshot_sync.cxx
Snapshot sync can call log compaction while committing is done at the same time in the background.
Commit bg thread goes into the loop of committing logs up to a certain log idx but during that, those logs could end up being compacted.
To prevent this, we pause the bg commit thread while sync is in progress.
No other place calls log compaction apart from the commit thread itself.
=> Fix segfault during snapshot install

include/libnuraft/raft_server.hxx, src/handle_commit.cxx, tests/unit/raft_server_test.cxx
In my case snapshot creation is asynchronous , we want to know when creation is done.
1. `create_snapshot` return `ulong` which is back forward compatible
2. add API `snapshot_created`
=> Make manually create snapshot result knowable

src/handle_join_leave.cxx, src/handle_vote.cxx
* If a removed server couldn't get the config that it was removed, it tries to do pre-vote. Soon it will receive "abandoned" messages from the existing members and step it down.
* Before stepping down itself, it should invoke the same callback as in the normal path.
=> Invoke `RemovedFromCluster` callback on pre-vote rejection

.gitignore, CMakeLists.txt, examples/calculator/calc_server.cxx
1、 fix ssl library path not found in my mac m1.
2、fix example npe bugs.
=> fix calc_sever print_status npe bug

src/handle_append_entries.cxx
I was not sure about it, but the previous lines suggest "index".
=> Fix a typo "idnex" -> "index"

examples/in_memory_log_store.hxx, include/libnuraft/event_awaiter.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/snapshot_sync_ctx.hxx, src/global_mgr.cxx, src/handle_append_entries.cxx, src/handle_client_request.hxx, src/handle_join_leave.cxx, src/handle_priority.cxx, src/handle_snapshot_sync.cxx, src/handle_timeout.cxx, src/handle_user_cmd.cxx, src/handle_vote.cxx, src/raft_server.cxx, src/snapshot_sync_ctx.cxx, tests/unit/asio_service_test.cxx, tests/unit/failure_test.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* Since it is used by the in-memory log store for examples, we need to move it to the public include directory.
=> Move `event_awaiter` class definition to public directory

include/libnuraft/log_val_type.hxx
We can see that the "custom" entrie of the log_val_type enum is set to 999. However, when this value is serialized, it is cast as 8bit unsigned integer which maximum value is 255.
We type the enumeration to 8bit interger and we change the value of custom to 999 (given that 999 % 256 = 231).
#400
=> Fix possible integer overflow when serializing log_val_type.

src/tracer.hxx
fix Visual Studio build :
src\tracer.hxx(34): error C3646: '__attribute__': unknown override specifier
We use the Microsoft source-code annotation language (SAL) equivalent to __attribute__((format(printf, ...
=> fix Visual Studio build

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx
To avoid adding too many configuration parameters to the asio_service_options, two new callbacks were added:
- std::function<SSL_CTX* (void)> ssl_context_provider_server_;
- std::function<SSL_CTX* (void)> ssl_context_provider_client_;
Which provide preconfigured, ready to use SSL_CTX, so the clients of the library may configure contexts in any required way.
Ported from https://github.com/ClickHouse/NuRaft/pull/56
=> Allowing clients to provide pre-Configured SSL_CTX for both client and server use-cases.

include/libnuraft/cluster_config.hxx, src/cluster_config.cxx, src/handle_join_leave.cxx, src/raft_server.cxx
Currently one must const_cast a cluster_config in order to iterate the servers it contains. This is done potentially during commit_conf or snapshots if one does not use the serialize/deserialize methods.
=> Allow get_servers() on const cluster_config

src/raft_server.cxx
* Log will be printed out for every second.
=> Do not generate verbose logs for corrupted log store

src/asio_service.cxx, src/handle_append_entries.cxx
* If `append_entries` is declined by callback, not by term mismatch, the leader should not do log rewind.
* Also, if it is declined by callback, the follower should not initiate leader election not to disrupt the entire cluster.
=> Don't do log rewind if `append_entries` is declined by callback

include/libnuraft/log_store.hxx, include/libnuraft/raft_server.hxx, src/handle_commit.cxx
* Log compaction is a disk IO intensive task, so we want to avoid executing it inside Raft's `lock_`.
* For that purpose, added an API to compact log asynchronously. `compact_async` can return immediately, and a callback will be invoked on the completion of the log compaction.
=> Add `compact_async` API to log store

include/libnuraft/raft_server.hxx, src/handle_snapshot_sync.cxx, src/raft_server.cxx
The RPC service can deadlock the background thread during snapshot creation and synchronization. Both race to take the lock_ mutex, but the RPC service will hold it while waiting for the snapshot to complete (which it never will). The loop that checks for snapshot progress needs to give up this lock.
=> Fix Deadlock between snapshot_sync_req and background snapshot creation.

src/mock_ssl.hxx
Added executor type to mock_ssl_socket.
=> fix build under Linux for non-SSL mode

src/handle_vote.cxx
* If zero-priority leader option is off, it should not become a leader even though the cluster size is 1 or the quorum size is adjusted.
=> Fix to bug that zero-priority member becomes leader

include/libnuraft/raft_server.hxx, src/handle_priority.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
`set_priority` is a bit inconsistent with `add_srv` and `remove_srv`.
If you invoke the latter two on a follower, the request will be
forwarded to leader. You can wait on the request and check whether it was accepted or not. 
Unfortunately, there are no such guarantees for `set_priority`.
If you invoke it on a follower, and there is a live leader, function would quit. 
I want to know the result of `set_priority`, so changes are proposed that change its return type.
=> Return status of set_priority. Ability to broadcast priority changes if there's a leader

include/libnuraft/asio_service_options.hxx, include/libnuraft/callback.hxx
Hi, this MR is meant to fix compilation issues with gcc 13 (added missing headers).
I'd also suggest to qualify `uint64_t` and similar types/entities in C++ code with `std::`, for the rationale see https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2340r1.html
=> Fix GCC 13 compile errors

include/libnuraft/callback.hxx, src/handle_append_entries.cxx, src/handle_vote.cxx
* When cluster size is 2 and `auto_adjust_quorum_for_small_cluster_` is on, the quorum size will be automatically adjusted to 1 when the other member is not responding. In such a case, we want to ask callback function whether we can adjust the quorum size or not.
=> Make callback be able to reject auto quorum size adjustment

include/libnuraft/raft_server.hxx, src/handle_join_leave.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/raft_server_test.cxx
* When a new leader is elected, the new leader's state machine may not fully catch up with the latest log index. In such a case, there will be a small time window for the leader's state machine to return stale data while it lags behind the latest log index.
* To check whether the state machine is lagging behind the latest log index when it became a leader, added a new API.
=> Add a new API to get the index at becoming leader

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx, tests/unit/asio_service_test.cxx
* It will be useful to pass the original request or response to meta callback functions.
=> Pass original request and response to meta callback

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_package_asio.hxx
* So far, CRC validation has been done on the message header, excluding the user payload like log entries.
* Added a new Asio service option to enable CRC validation on the entire message. It is disabled by default for backward compatibility.
* Also added a callback function that can be invoked on any corrupted message, so as to do more investigation on user application side.
* Removed direct buffer get/put API calls, instead refactored the code with `buffer_serializer`.
=> Support CRC validation on entire message

CMakeLists.txt, NuRaftConfig.cmake.in
This exports both the shared and static library targets. A downstream project can use then use them as follows:
```cmake
find_package(NuRaft REQUIRED)
target_link_libraries(downstream_target PRIVATE NuRaft::static_lib)
```
Closes #450
=> Export CMake targets

CMakeLists.txt
This refactors CMakeLists.txt to call find_package() instead of using our own detection logic. The result is easier to read, and will benefit from improvements to the FindOpenSSL module, which is battle-hardened.
The following options' behavior was preserved:
DEPS_PATH, OPENSSL_INCLUDE_PATH, and OPENSSL_LIBRARY_PATH.
The change was implemented on OS X, so the developer was able to verify that Homebrew's OpenSSL1.1 can be detected after the change.
This is continuing the work started in #358.
=> Use find_package for OpenSSL detection

CMakeLists.txt, examples/in_memory_log_store.cxx, include/libnuraft/asio_service_options.hxx, include/libnuraft/log_entry.hxx, src/asio_service.cxx, src/log_entry.cxx, tests/unit/raft_package_asio.hxx
Add an option to replicate and verify per-log-entry CRC checksums.
The log entry's checksum is computed when the entry is first created on the leader, and then stored in the log store and replicated over the network. On receive, if the checksum is sent, it is verified.
=> Add optional CRC per log entry.

CMakeLists.txt
This makes usage consistent. NuRaft::target_name will always work regardless of whether NuRaft was set up as a subdirectory or loaded from a config.
Fixes #459.
=> Add missing alias targets to CMakeLists

CMakeLists.txt
This adds the include directory to the public includes for both the static and shared targets. It is necessary to do it for both the build and install interfaces, because the build interface will be used if the project is added as a submodule, but the install interface will be used if the project was added using a config.
Fixes #460.
=> Fix public usage requirements on CMake targets

src/mock_ssl.hxx
* Instead of `int`, use the definition from Asio.
* Resolves #238
=> Fix `executor_type` in `mock_ssl`.

include/libnuraft/state_machine.hxx, src/handle_append_entries.cxx
* State machine API should be invoked for not only app logs, but also config logs, not to miss any index number.
=> Add `rollback_config` API to state machine

include/libnuraft/callback.hxx, src/handle_join_leave.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
If we `add_srv`, what we can check is that a command was accepted. However, the only way to check whether it was applied is to query replica's config. In case of server not being added (e.g. non-existent host) we will never find this server in a config.
This PR proposes a way to handle such corner cases without relying on some arbitrary timeouts
Note we don't need a ServerLeaveFailed callback as a server that fails to be removed gracefully is still removed.
=> ServerJoinFailed callback

src/handle_join_leave.cxx, src/handle_timeout.cxx, tests/unit/raft_server_test.cxx
* If a member receiving snapshot is not responding, and then removed by the rpc error handler, its snapshot ctx is kept open and will never be closed.
* To avoid such an issue, rpc error handler should explicitly destroy the snapshot ctx of the removed member.
=> Fix to bug on snapshot ctx of removed member

include/libnuraft/callback.hxx, src/handle_commit.cxx, tests/unit/raft_functional_common.hxx, tests/unit/raft_server_test.cxx
* Since snapshot is created by the background commit thread, index inversion can happen if user explicitly calls manual creation API. In that case, the backgroudn thread will create a snapshot on an index that is older than the latest snapshot, which should not happen.
* To avoid such a case, added a logic to check the request commit index and the latest snapshot's index.
=> Avoid snapshot creation index inversion

README.md, include/libnuraft/raft_server.hxx, src/handle_commit.cxx, src/raft_server.cxx, tests/unit/raft_server_test.cxx
* Added `schedule_snapshot_creation()` API to manually create a snapshot.
* Unlike `create_snapshot()`, if snapshot creation is already in progress, it will wait and create another snapshot on the next available log index number.
=> Add an API to schedule snapshot creation

src/handle_append_entries.cxx
Conditions:
1、cluster has only 2 nodes
2、leader yield_leadership
3、option auto_adjust_quorum_for_small_cluster_ is true
4、anthor node become leader and old leader down
5、cluster is idle
Pending cluster configuration has no chance to commit
=> Commit is needs to be triggered when quorum size becomes 1

src/handle_join_leave.cxx
This a pull request for fixing the problem mentioned in issue #233 
I've added an additional check to prevent a node from joining multiple clusters.
=> <fix>: prevent a server joining another cluster whlit it is already in one.

include/libnuraft/msg_type.hxx, src/asio_service.cxx
* If there is an incoming random message, where `CRC_ON_ENTIRE_MESSAGE` flag is randomly set, NuRaft tries to read the entire message for CRC check. That requires allocating a memory blob with the given size (also a random number) which most likely causes problem.
* Added more sanity checks before the memory allocation.
=> Add more sanity checks on a new connection

examples/calculator/calc_state_machine.hxx
* Once reading snapshot request fails, the state machine should return a negative number, not 0.
=> Fix to the wrong example in `calc_state_machine.hxx`

src/asio_service.cxx
If the network goes down during a async_connect, we may end up being stuck forever in this function since there is no timeout to cancel it.
=> Add timeout to async_connect operation

include/libnuraft/async.hxx, src/asio_service.cxx
In some cases, the response is marked as accepted even if there was an error. Therefore, including the accepted tag in the response message is not enough: a follower may believe that an auto forwarded request was successful when it wasn't.
Resolves #513
=> Add result code to response messages

include/libnuraft/callback.hxx, include/libnuraft/peer.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/raft_server.cxx
Hello, within this PR we suggest to introduce a new `cb_func::Type` enum item: `FollowerLost`, and, on detection of follower loss, call the callback function with the `type` parameter equal to `FollowerLost`.
Pavel Yurin, 
C++ developer
NXLog Ltd.
pavel.yurin@nxlog.org
www.nxlog.co
=> Notify user code about follower loss

include/libnuraft/raft_server.hxx, src/raft_server.cxx
Opening PR as per issue https://github.com/eBay/NuRaft/issues/522
=> Use leadership_expiry_ to deem nodes unhealthy

src/handle_client_request.cxx
* When a leader invokes `end_of_append_batch`, the first parameter represents the starting index of the batch. There was missing `+1`.
=> Fix to bug in `handle_cli_req`

.github/workflows/cmake.yml, include/libnuraft/asio_service_options.hxx, scripts/test/runtests.sh, src/asio_service.cxx, tests/CMakeLists.txt, tests/unit/asio_service_stream_test.cxx
1. set TCP_NODELAY = true this can be set after the socket open. So we can't set it in constructor. (async_connect will open the socket)
2. does the order of calling all the when_done matter when error occur? in write path when_done(error triggered) -> close_socket(in destructor) in read path close_socket(directly call) -> when_done(error triggered)
3. keep the old path for all request if stream_mode_ = false
already addressed all the comment.
=> asio_service support stream mode

tests/unit/asio_service_stream_test.cxx
1. client send requests to wrong endpoint
2. client is closed after sending requests
3. server timeout after sending requests
4. server is closed after sending requests
=> Enhance test for stream asio

include/libnuraft/peer.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, scripts/test/runtests.sh, src/handle_append_entries.cxx, src/peer.cxx, tests/CMakeLists.txt, tests/unit/asio_stream_test.cxx, tests/unit/raft_package_asio.hxx
add an additional flag: flying_append_entry_request.
it is used to present if it is the first request. if streaming is disable in the middle, we can only send the new request when flying request = 0
=> Implement stream mode in peer and raft server(a proposal)

src/handle_commit.cxx
Fixes #533 in issues. Fixes minor typo 'curruent' -> 'current' in `src/handle_commit.cxx`
=> typo: src/handle_commit.cxx fix to current idx; issue #533

CMakeLists.txt, src/exit_handler.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_snapshot_sync.cxx, src/raft_server.cxx
Allow the process to handle termination of raft service rather than force process wide `exit()`
Addresses #535
=> Use pthread_exit to terminate raft service.

include/libnuraft/callback.hxx, src/handle_append_entries.cxx
* Callback can decide whether to ignore or to die.
=> Add a callback to handle misbehaving messages from peer

src/handle_commit.cxx
In one of our tests, NuRaft ended up creating 2 snapshots with a distance of 1 log.
I didn't find anything strange in the logs:
```
2024.09.28 03:34:06.424741 [ 606 ] {} <Debug> RaftInstance: commit upto 50, current idx 49
2024.09.28 03:34:06.424773 [ 606 ] {} <Trace> RaftInstance: commit upto 50, current idx 50
2024.09.28 03:34:06.424871 [ 606 ] {} <Information> RaftInstance: creating a snapshot for index 50
2024.09.28 03:34:06.424891 [ 606 ] {} <Information> RaftInstance: create snapshot idx 50 log_term 1
2024.09.28 03:34:06.424897 [ 605 ] {} <Debug> RaftInstance: Receive a append_entries_response message from peer 3 with Result=1, Term=1, NextIndex=51
2024.09.28 03:34:06.425021 [ 596 ] {} <Debug> RaftInstance: Receive a append_entries_response message from peer 2 with Result=1, Term=1, …
```
=> Fix checking distance of last snapshot

CMakeLists.txt, include/libnuraft/peer.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/srv_config.hxx, scripts/test/runtests.sh, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_timeout.cxx, src/handle_vote.cxx, src/raft_server.cxx, src/srv_config.cxx, tests/CMakeLists.txt, tests/unit/new_joiner_test.cxx
* A new setting, `use_new_joiner_type_`, has been introduced, which defaults to false.
* When activated, any new members are immediately added to the cluster configuration as a "new joiner." Similar to learners, new joiners do not participate in the quorum; they cannot initiate or partake in voting.
* Once the log gap of a new joiner narrows to less than `log_sync_stop_gap_`, the member transitions to a regular status and becomes eligible to engage in the leader election process.
* The advantage of this feature is that it allows a newly elected leader to continue the synchronization process with the new joiner without needing to invoke the `add_srv()` API again.
=> Support new joiner functionality

include/libnuraft/peer.hxx, include/libnuraft/raft_params.hxx, src/handle_append_entries.cxx, src/peer.cxx, tests/unit/stream_functional_test.cxx
1. Add track for flying bytes
2. Add a new throttling flying bytes
=> Add flying_bytes for throttling.

src/asio_service.cxx
`remaining_len` can be `> 0` if there is result code we didn't read yet
so it incorrectly concluded if context is present
=> Read context for response only if present

include/libnuraft/raft_server.hxx, src/handle_client_request.cxx, src/raft_server.cxx
On config changes, the precommit index will be updated instantly to index of config change.
After it, `request_append_entries` is called which instantly commits up to `precommit` index if a node was removed from 2-node cluster.
If logs were being applied at the same time it could lead to commit thread trying to commit logs that were still not precommitted.
I couldn't find another explanation for such scenario.
If my conclusions are wrong feel free to correct me. :pray: 
I also couldn't find a better way to fix it quickly.
=> Fix race on precommit when cluster is changed

src/asio_service.cxx
We detected a data race with one of our tests
https://pastila.nl/?0003c12b/68530aca8742766996176fdebcede8dc#KBCq01QCyL4Qz2lDbsNzrA==
It's insanely hard to parse all that asio stacktrace but the race happens on `operation_timer_` inside `async_resolve` callback.
My theory is that `async_connect` got resolved and had its callback called before we setup the timer and started it.
So the problem should be solved with moving timer setup before we start the `async_connect`.
Now for the general issue.
Asio in NuRaft is run with a single io context on multiple threads. This can lead to data races in general (e.g. timer calls `socket.cancel()`). I'm not sure if `cancel` on socket is threadsafe (I assume it's not) but to avoid similar problems shouldn't `strand` be used for a single …
=> Fix data race in asio service

include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_join_leave.cxx, src/handle_snapshot_sync.cxx, src/raft_server.cxx
Add a dedicated timeout for snapshot_sync_ctx, and user can set this value in raft_param.
=> Add timeout for snapshot_sync_ctx

include/libnuraft/raft_server.hxx, include/libnuraft/srv_state.hxx, src/handle_append_entries.cxx, src/handle_commit.cxx, src/handle_join_leave.cxx, src/handle_snapshot_sync.cxx, src/handle_timeout.cxx, src/handle_vote.cxx, src/raft_server.cxx, tests/unit/fake_network.cxx, tests/unit/raft_package_fake.hxx, tests/unit/raft_server_test.cxx
* If a new member joins a cluster but restarts while receiving the snapshot, its `catching_up_` flag will be cleared, causing the join process to stall.
* To prevent this issue, the `catching_up_` flag will be stored as part of the `srv_state`. After the server restarts, the leader and the server will attempt the snapshot transmission again.
* The `srv_state` format has been changed, but it will remain backward compatible.
=> Make `catching_up_` flag durable

include/libnuraft/raft_server.hxx, src/handle_vote.cxx, src/raft_server.cxx
* If a connection is stuck due to a network black hole or similar issues, the sender may not receive either a response to the previous request or an explicit error, preventing any progress through that connection.
* Such situations are unlikely to resolve on their own, and sometimes restarting the process is the only solution. If the connection remains busy beyond a certain threshold, `system_exit` will be invoked with `N22_unrecoverable_isolation`.
=> Do `system_exit` on recurring pre-vote failure due to busy connection

src/handle_vote.cxx
* We should check whether # busy connections + min quorum size is greater than # voting members. The current condition (# busy connections >= min quorum size) is wrong.
=> Fix to incorrect quorum size calculation for busy connection

include/libnuraft/raft_server.hxx, src/handle_commit.cxx
* The only current option is to serialize commits to ensure that snapshots are created using the latest log index.
=> Add options for `create_snapshot` API

src/handle_snapshot_sync.cxx
If the server was previously in the member set which was captured in the config of this snapshot, then the peer will appear to have "caught_up" in ::reconfigure. I do not believe there is value in rolling back the config just to reapply it later once log_sync occurs. `::commit_conf` performs a similar check.
=> Fix: The snapshot installation blindly applies config to the server.

include/libnuraft/peer.hxx, src/asio_service.cxx, src/handle_append_entries.cxx, src/peer.cxx, src/raft_server.cxx
* If connection is suddenly closed before handling the response, queue may become empty when a callback function is invoked. It should be handled safely.
* Added more logs regarding streaming mode.
=> Fix bugs in streaming mode

include/libnuraft/raft_server.hxx, include/libnuraft/srv_config.hxx, src/handle_user_cmd.cxx, src/raft_server.cxx, tests/unit/asio_service_test.cxx
Previously, learner is a static srv config, provide a cmd for use to flip the learner flag.
=> Support learner change

include/libnuraft/asio_service_options.hxx, src/asio_service.cxx, tests/unit/asio_service_test.cxx, tests/unit/raft_package_asio.hxx
* Added `custom_io_context_` to `asio_service_options`. If it is given, `asio_service` will not create the internal threads. The user is responsible for managing the thread pool and handling the async tasks and timers requested by NuRaft.
=> Support external thread pool

include/libnuraft/raft_server.hxx
`set_raft_limits` uses assignment operator so you couldn't change busy limit with it.
=> Fix changing busy connection limit

src/peer.cxx, src/raft_server.cxx, tests/unit/snapshot_test.cxx
* If disconnection or leader election happens, the very first message should be `append_entries` so as to check whether we should send the snapshot again or not.
=> Reset `snapshot_sync_is_needed` on disconnection or leader election

include/libnuraft/raft_server.hxx, src/handle_commit.cxx, src/handle_snapshot_sync.cxx, tests/asio/asio_service_test.cxx
* If `pause_state_machine_exeuction` is invoked while the state machine is lagging behind the latest log of the log store, it will end up with an infinite loop.
=> Fix to pause state machine bug

CMakeLists.txt, include/libnuraft/raft_server.hxx, scripts/test/runtests.sh, src/handle_commit.cxx, src/raft_server.cxx, tests/CMakeLists.txt, tests/unit/learner_new_joiner_test.cxx, tests/unit/raft_package_fake.hxx
* We can update server config through that API, instead of removing and re-adding the server with updated config.
* Learner flag, DC ID, aux, and priority can be changed on-the-fly, while endpoint is immutable.
=> Add `update_srv_config` API

include/libnuraft/peer.hxx, include/libnuraft/raft_server.hxx, include/libnuraft/req_msg.hxx, include/libnuraft/resp_msg.hxx, src/asio_service.cxx, src/handle_append_entries.cxx, src/raft_server.cxx, tests/asio/custom_quorum_test.cxx
* Followers can mark itself down for the case of shutting down or stepping down the server.
* Followers can recognize itself whether it is part of the quorum or not (so that it has the latest log or not).
* Leader can exclude followers that are either not responding for a certain period of time, or lagging behind even though it is responding.
=> Support automated full consensus

include/libnuraft/async.hxx, include/libnuraft/peer.hxx, include/libnuraft/raft_params.hxx, include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/handle_client_request.cxx, src/handle_client_request.hxx, src/handle_commit.cxx, src/raft_server.cxx, tests/asio/custom_quorum_test.cxx
* Added `wait_for_state_machine_commit`, that will notify the user when the state machine commits the required log index via the given callback.
=> Add an API to subscribe state machine's commit

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx, src/raft_server.cxx, tests/asio/custom_quorum_test.cxx
* If heartbeat is extremely slow, there can be an edge case that the follower is excluded but the follower recognizes itself as a part of quorum. It should be handled gracefully.
=> Fix an edge case of full consensus mode

include/libnuraft/internal_timer.hxx, src/raft_server.cxx, tests/asio/custom_quorum_test.cxx
* If a server is stopped, term is increased, and the server starts again, it should not recognize itself as the part of consensus, until it receives the first valid message from the leader.
=> Fix to edge case of full consensus mode

include/libnuraft/raft_server.hxx, src/handle_append_entries.cxx
* In stream mode, don't need to send an additional catch-up message for peer state machine commit index tracking purpose. The in-flight stream message will carry the most recent information.
=> Do not send catch-up message in stream mode
